# Generated by Django 5.0.6 on 2024-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_sale_sale_detail_sales_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
