# Generated by Django 5.0.6 on 2024-07-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='Total',
            new_name='total',
        ),
    ]
