# Generated by Django 5.0.6 on 2024-07-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_rename_discount_sale_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
    ]
